In [5]:
%pip install numpy pandas duckdb

Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.2)
Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: duckdb in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 54.9 MB/s  0:00:006m0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import duckdb

conn = duckdb.connect("main.db")
conn.execute("CREATE TABLE IF NOT EXISTS air_quality AS " \
            "SELECT * FROM '/workspaces/Product-Market-Fit-Analysis---Case-Study/Dataset/day-wise-state-wise-air-quality-index-aqi-of-major-cities-and-towns-in-india.csv'")

conn.execute("SELECT * FROM air_quality LIMIT 5").fetchdf()

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,note
0,2025-06-19,Uttar Pradesh,Agra,5.0,"O3,PM2.5,PM10",49.0,Good,number_of_monitoring_stations in Absolute Numb...,None
1,2025-06-19,Karnataka,Bagalkot,1.0,PM10,46.0,Good,number_of_monitoring_stations in Absolute Numb...,None
2,2025-06-19,Maharashtra,Akola,1.0,PM10,26.0,Good,number_of_monitoring_stations in Absolute Numb...,None
3,2025-06-19,Rajasthan,Alwar,1.0,CO,76.0,Satisfactory,number_of_monitoring_stations in Absolute Numb...,None
4,2025-06-19,Andhra Pradesh,Amaravati,1.0,PM10,66.0,Satisfactory,number_of_monitoring_stations in Absolute Numb...,None

In [2]:
conn.execute("""
CREATE TABLE IF NOT EXISTS disease_data AS
SELECT *
FROM read_csv(
    '/workspaces/Product-Market-Fit-Analysis---Case-Study/Dataset/master-data-state-district-and-disease-wise-cases-and-death-reported-due-to-outbreak-of-diseases-as-per-weekly-reports-under-idsp.csv',
    ignore_errors=true
             )
""")
conn.execute("SELECT * FROM disease_data LIMIT 5").fetchdf()

,year,week,outbreak_starting_date,reporting_date,state,district,disease_illness_name,status,cases,deaths,unit,note
0,2025,14,2025-04-05,2025-04-05,Assam,Biswanath,Food Poisoning,Reported,18,0,"cases in absolute number, deaths in absolute n...",None
1,2025,14,2025-04-03,2025-04-04,Bihar,Aurangabad,Fever with Rash,Reported,21,0,"cases in absolute number, deaths in absolute n...",None
2,2025,14,2025-03-31,2025-04-04,Bihar,Madhubani,Chickenpox,Reported,14,0,"cases in absolute number, deaths in absolute n...",None
3,2025,14,2025-04-03,2025-04-04,Gujarat,Bhavnagar,Food Poisoning,Reported,20,0,"cases in absolute number, deaths in absolute n...",None
4,2025,14,2025-04-01,2025-04-01,Gujarat,Vadodara,Acute Diarrheal Disease,Reported,20,0,"cases in absolute number, deaths in absolute n...",None

In [3]:
conn.execute("""
CREATE TABLE IF NOT EXISTS vehicle_registrations AS
SELECT *
FROM read_csv(
    '/workspaces/Product-Market-Fit-Analysis---Case-Study/Dataset/master-data-state-vehicle-class-and-fuel-type-wise-total-number-of-vehicles-registered-in-each-month-in-india.csv',
    ignore_errors=true
             )
""")
conn.execute("SELECT * FROM vehicle_registrations LIMIT 5").fetchdf()

,year,month,state,rto,vehicle_class,fuel,value,unit,note
0,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,BUS,DIESEL,2,value in Absolute Number,None
1,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,GOODS CARRIER,DIESEL,23,value in Absolute Number,None
2,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,GOODS CARRIER,PETROL,1,value in Absolute Number,None
3,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,M-CYCLE/SCOOTER,ELECTRIC(BOV),1,value in Absolute Number,None
4,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,M-CYCLE/SCOOTER,PETROL,387,value in Absolute Number,None

In [4]:
conn.execute("""
CREATE TABLE IF NOT EXISTS population_data AS
SELECT *
FROM read_xlsx(
    '/workspaces/Product-Market-Fit-Analysis---Case-Study/Dataset/population-projection-of-india-state-and-gender-wise-yearly-projected-urban-population-2011-2036.xlsx',
    ignore_errors=true
             )
""")
conn.execute("SELECT * FROM population_data LIMIT 5").fetchdf()

     year    month        state  gender    value                unit  note
0  2036.0  October  West Bengal   Total  43964.0  value in Thousands   NaN
1  2036.0  October  West Bengal    Male  22615.0  value in Thousands   NaN
2  2036.0  October  West Bengal  Female  21349.0  value in Thousands   NaN
3  2036.0  October  Uttarakhand   Total   5506.0  value in Thousands   NaN
4  2036.0  October  Uttarakhand    Male   2922.0  value in Thousands   NaN

In [5]:
"""
Q1. List the top 5 and bottom 5 areas with highest average AQI. 
(Consider areas which contains data from last 6 months: December 2024 to May 2025)
"""

conn.execute(""" 
            SELECT * FROM air_quality
            WHERE date >= '2024-12-01' AND date <= '2025-05-31'
             
    """).fetchdf()

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,note
0,2025-05-31,Rajasthan,Hanumangarh,1.0,PM10,148.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
1,2025-05-31,Gujarat,Vatva,1.0,PM10,72.0,Satisfactory,number_of_monitoring_stations in Absolute Numb...,None
2,2025-05-31,Tamil Nadu,Hosur,1.0,PM10,59.0,Satisfactory,number_of_monitoring_stations in Absolute Numb...,None
3,2025-05-31,Rajasthan,Baran,1.0,PM10,101.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
4,2025-05-31,Maharashtra,Pimpri Chinchwad,4.0,"PM10,O3",144.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
...,...,...,...,...,...,...,...,...,...
41610,2024-12-01,Haryana,Kaithal,1.0,PM10,133.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
41611,2024-12-01,Haryana,Dharuhera,1.0,PM2.5,180.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
41612,2024-12-01,Kerala,Eloor,1.0,PM2.5,82.0,Satisfactory,number_of_monitoring_stations in Absolute Numb...,None
41613,2024-12-01,Rajasthan,Bhiwadi,2.0,PM2.5,158.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None
41614,2024-12-01,Uttar Pradesh,Prayagraj,3.0,"PM2.5,PM10",122.0,Moderate,number_of_monitoring_stations in Absolute Numb...,None